version: '3'
services:
  cindi:
    image: cindi:1.0.1-alpha
    environment:
      - "Cluster:Urls=http://localhost"
      - "Cluster:MinimumNodes=1"
      - "Client:apiUrl=http://localhost:5021"
      - "Logging:Default:Debug"
      - "Logging:File:Enabled=true"
      - "Logging:File:LogDirectory=/var/log/cindi"
    ports:
      - 5021:80
    volumes:
      - mongodata:/data/db
      - C:\\Users\\TNguy\\Downloads\\logs:/var/log/cindi
  #mongod11b:
  #  image: mongo:latest
  #  volumes:
  #    - mongodata:/data/db
volumes:
  mongodata:
  logs: