version: '3'
services:
  cindi:
    image: cindi:1.1
    environment:
      - "Cluster:Urls=http://localhost"
      - "Cluster:MinimumNodes=1"
      - "Client:apiUrl=http://localhost:5021"
    ports:
      - 5021:80
    volumes:
      - mongodata:/data/db
  #mongod11b:
  #  image: mongo:latest
  #  volumes:
  #    - mongodata:/data/db
volumes:
  mongodata: