version: '3'
services:
  cindi:
    image: cindi:1.0
   # environment:
      #- "DBConnectionString=mongodb://mongodb:27017"
    ports:
      - 5022:80
    volumes:
      - mongodata:/data/db
  #mongodb:
  #  image: mongo:latest
  #  volumes:
  #    - mongodata:/data/db
volumes:
  mongodata: