version: '3'
services:
  cindi:
    image: xucito/cindi:2.0.0-alpha-3a55f52
    environment:
      - "Cluster:NodeUrls=https://localhost:5021"
      - "Cluster:MinimumNodes=1"
      - "Client:apiUrl=https://localhost:81"
      - "Logging:LogLevel:Default=Information"
      - "Logging:Default=Debug"
      - "Logging:File:Enabled=true"
      - "Logging:File:LogDirectory=/var/log/cindi"
    ports:
      - 81:5021