version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongotest:/data/db
    ports:
      - 27018:27017
  mongodb-2:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
volumes:
  mongotest:
  mongodata: