version: '3.7'
services:
  cindi-1:
    image: cindi:1.1.2
    container_name: cindi
    environment:
      - "Cluster:NodeUrls=http://cindi_cindi-1,http://cindi_cindi-2,http://cindi_cindi-3"
      - "Cluster:MinimumNodes=2"
      - "Client:apiUrl=http://localhost:5021"
      - "Logging:Default:Debug"
      - "Logging:File:Enabled=true"
      - "Logging:File:LogDirectory=/var/log/cindi"
    ports:
      - 5021:80
    deploy:
      restart_policy:
        condition: any
    networks:
      - overlay
  cindi-2:
    image: cindi:1.1.2
    container_name: cindi
    environment:
      - "Cluster:NodeUrls=http://cindi_cindi-1,http://cindi_cindi-2,http://cindi_cindi-3"
      - "Cluster:MinimumNodes=2"
      - "Client:apiUrl=http://localhost:5021"
      - "Logging:Default:Debug"
      - "Logging:File:Enabled=true"
      - "Logging:File:LogDirectory=/var/log/cindi"
    ports:
      - 5022:80
    deploy:
      restart_policy:
        condition: any
    networks:
      - overlay
  cindi-3:
    image: cindi:1.1.2
    container_name: cindi
    environment:
      - "Cluster:NodeUrls=http://cindi_cindi-1,http://cindi_cindi-2,http://cindi_cindi-3"
      - "Cluster:MinimumNodes=2"
      - "Client:apiUrl=http://localhost:5021"
      - "Logging:Default:Debug"
      - "Logging:File:Enabled=true"
      - "Logging:File:LogDirectory=/var/log/cindi"
    ports:
      - 5023:80
    deploy:
      restart_policy:
        condition: any
    networks:
      - overlay
networks:
  overlay: